### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [minnukota381/Quantum-Computing-Qiskit#1]
I recently came across your project Quantum-Computing-Qiskit and I noticed that the repository github.com/minnukota381/Quantum-Computing-Qiskit currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by minnukota381** [comment]
I have fixed this in : 3ad2e4d89732a3af0bbf801558a9e0dc590153d1

**Comment by minnukota381** [comment]
Thanks you so much for your contribution sir!

**Comment by cbjuan** [comment]
Thank you!

**Comment by minnukota381** [comment]
Sir! I’m currently working on a few small projects in quantum computing, and I’d love to hear more about what you’re working on at IBM and how quantum is being applied in real-world scenarios. Could you please connect with me sir?
